# Generated by Django 4.0.4 on 2022-05-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_libreria', '0002_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='libro',
        ),
        migrations.AddField(
            model_name='carrito',
            name='listaLibros',
            field=models.ManyToManyField(to='app_libreria.libro'),
        ),
    ]
