# Generated by Django 4.0.4 on 2022-05-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_libreria', '0003_remove_carrito_libro_carrito_listalibros'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='totalPagar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
