# Generated by Django 4.0.4 on 2022-05-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_libreria', '0004_carrito_cantidad_carrito_totalpagar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='totalPagar',
        ),
    ]
